name: Build & Deploy to S3

on:
  push:
    branches: [ "main" ]   # deploy when you push to main
  workflow_dispatch:       # allow manual runs from the Actions tab

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Ensure SPA routing works (index.html fallback)
      - name: Ensure S3 website config (index + error = index.html)
        run: |
          aws s3 website s3://${{ secrets.S3_BUCKET }} --index-document index.html --error-document index.html

      - name: Sync build to S3
        run: |
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }} --delete
